### ISSUE TITLE
Алиасы к базам данных

### ISSUE THREAD

**Issue by Evil1991** [mefist1990/pwfooterbigmodule#1]
https://github.com/mefist1990/pwfooterbigmodule/blob/837d76ee507f52976db895d9941295b6c3243891/pwfooterbigmodule.php#L203

Алиасы всегда называем по буквам таблиц, т.е. для category_lang нужен cl, а не pwcl

**Comment by mefist1990** [comment]
Ок понял, поправил + генератор + фик линки
https://github.com/mefist1990/pwfooterbigmodule/commit/2da68926ece7a6ce2022060f5de577740b7ea673
