### ISSUE TITLE
Усложнение с переменными

### ISSUE THREAD

**Issue by Evil1991** [mefist1990/pwfooterbigmodule#10]
https://github.com/mefist1990/pwfooterbigmodule/blob/65c5202a8f048520b0661f2afcc80c7ceb7287ff/pwfooterbigmodule.tpl#L105

1. Если все это для того, чтобы разобрться выводить запятые или нет, то можно проще, просто условия вида {if Configuration::get('')}, {/if}

**Comment by mefist1990** [comment]
https://github.com/mefist1990/pwfooterbigmodule/commit/5ac29d6d2247636415b64e30a90afeef5a67094f
