### ISSUE TITLE
Константы

### ISSUE THREAD

**Issue by Evil1991** [mefist1990/pwfooterbigmodule#2]
https://github.com/mefist1990/pwfooterbigmodule/blob/af9bd0962decde5545144317e4735f6f1fb234a7/pwfooterbigmodule.php#L277

Любые прямые значения в коде - опасны, почему id_parent именно 2?

Для этой переменной есть своя опция, поищи в примерах, например blockcategories

Тоже самое касается id_shop + для мультимагазинов есть такие строки http://prntscr.com/jsdj9x, лучше использовать их

**Comment by mefist1990** [comment]
Да я это в курсе -  этот код + форматирование я буду исправлять в конце, когда закончу основной модуль, сделал специально чтобы точно получить данные для моего магазина, чтобы найти правильное решение. На будущее буду помечать спорные места, которые потом подправлю, комментарием. Это принял во внимание)
