### ISSUE TITLE
Поправить код

### ISSUE THREAD

**Issue by Evil1991** [mefist1990/pwfooterbigmodule#3]
https://github.com/mefist1990/pwfooterbigmodule/blob/8e376eb3494c0d6d362d47c0e0303a56194725c1/pwfooterbigmodule.php#L587

1. Название функций надо начинать с маленькой буквы и слово function - избыточно, начинается почти всегда с метода, т.е. get, set, update и т.п. тут логичнее будет назвать getInformationColumn, так как и так понятно что речь про футер
2. Эти страницы нужно сделать, в неограниченном количестве, т.е. хранить записи о них в виде сериализованного массива в одной Configration
3. Следи пожалуйста за оформлением кода http://prntscr.com/jstgmc - лучше сразу работать в IDE

**Comment by mefist1990** [comment]
поставил phpshtorm, код отформатировал через автоматический формат в phpshtorm, все нюансы пофиксил.
