### ISSUE TITLE
Поправить переменные

### ISSUE THREAD

**Issue by Evil1991** [mefist1990/pwfooterbigmodule#4]
https://github.com/mefist1990/pwfooterbigmodule/blob/8e376eb3494c0d6d362d47c0e0303a56194725c1/pwfooterbigmodule.php#L690

Данные переменные не надо вызывать в php, можно прямо в шаблоне {Configuration::get('PS_SHOP_PHONE')}

**Comment by mefist1990** [comment]
Исправил
