### ISSUE TITLE
Нужно вызывать массивом

### ISSUE THREAD

**Issue by Evil1991** [mefist1990/pwfooterbigmodule#5]
https://github.com/mefist1990/pwfooterbigmodule/blob/8e376eb3494c0d6d362d47c0e0303a56194725c1/pwfooterbigmodule.php#L742

функция assign принимает на входе массив, поэтому для каждой переменной отдельно не надо её вызывтаь

**Comment by mefist1990** [comment]
https://github.com/mefist1990/pwfooterbigmodule/commit/d68f0ccc767b9e2423d754b3863a66e9037f7419
