### ISSUE TITLE
Создание нескольких страниц

### ISSUE THREAD

**Issue by Evil1991** [mefist1990/pwfooterbigmodule#6]
https://github.com/mefist1990/pwfooterbigmodule/blob/c5dc0375f90aa5a838c9b115bdc8b7c1ab976bb6/pwfooterbigmodule.php#L163

В данном случае подойдет, на будущее вот смотри более изящный вариант http://admin:altopromo@admin.leadget.ru/modules/rep/pwblockfavpage.zip

**Comment by mefist1990** [comment]
ООО. Я читал про это на форуме, искал в модулях стандартных данную реализацию, но не нашел. Изучу и буду применять в следующих плагинах, где нужна будет сложные настройки модуля.
