### ISSUE TITLE
Лишняя переменная

### ISSUE THREAD

**Issue by Evil1991** [mefist1990/pwfooterbigmodule#8]
https://github.com/mefist1990/pwfooterbigmodule/blob/c5dc0375f90aa5a838c9b115bdc8b7c1ab976bb6/pwfooterbigmodule.php#L416

в ней нет необходимости, убрать, использовать сразу вызов configuration

**Comment by mefist1990** [comment]
https://github.com/mefist1990/pwfooterbigmodule/commit/b9225e067c0b2529a6b5e7678d5c8012c9fe34c8
