### ISSUE TITLE
Избыточная функция

### ISSUE THREAD

**Issue by Evil1991** [mefist1990/pwfooterbigmodule#9]
https://github.com/mefist1990/pwfooterbigmodule/blob/c5dc0375f90aa5a838c9b115bdc8b7c1ab976bb6/pwfooterbigmodule.php#L282

Перенести в шаблон

**Comment by mefist1990** [comment]
https://github.com/mefist1990/pwfooterbigmodule/commit/b6e7ac416fad2bc803787d583246319cc32e141f
